spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    url: ${URL}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    liquibase: INFO
server:
  port : 80

bucketname : tradesman-bucket
region : us-east-2